name = "Juniper S11"
author = "orangc"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42eb4368b5a174f3f01366a91f1ce4d7ad4839796516da9b8edbf1267f215222"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
