name = "Juniper S11"
author = "orangc"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5222c02ea09a7dbe027a443ac9bd69cd0d285342526dadf66c01fa14f2bddd29"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
