name = "Juniper S11"
author = "orangc"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a1403ffc0b4dacc95e3de61a4d498a54a46536e099269322cd7eee23d532d04"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
