#Minecraft server properties
#Sat Jun 13 17:17:18 AST 2026
accepts-transfers=false
allow-flight=true
allow-nether=true
broadcast-console-to-ops=false
broadcast-rcon-to-ops=false
bug-report-link=mailto\:c@orangc.net
difficulty=hard
enable-command-block=true
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=false
enforce-whitelist=true
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=3
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla,fabric
level-name=world
level-seed=Mystia's Izakaya.
level-type=minecraft\:normal
log-ips=false
max-chained-neighbor-updates=1000000
max-players=20
max-tick-time=60000
max-world-size=50000
motd=§l  §r               §d§lJuniper §r— §a§lSeason XI§r\n§l §b§o                  Craftable fumos?\!
network-compression-threshold=256
online-mode=false
op-permission-level=4
pause-when-empty-seconds=300
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
query.port=25565
rate-limit=0
rcon.password=
rcon.port=7810
region-file-compression=deflate
require-resource-pack=false
resource-pack=
resource-pack-id=
resource-pack-prompt=
resource-pack-sha1=
server-ip=
server-name=Juniper
server-port=25565
simulation-distance=8
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=0
sync-chunk-writes=true
text-filtering-config=
use-native-transport=true
view-distance=16
white-list=false
