name = "Frontera217"
author = "orangc"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5dde49bd7bc8f42fec5d20f4f0cc5b6941a772c591d9eabb912e546af8504c99"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"

[options]
acceptable-game-versions = ["1.21.6"]
