name = "Frontera217"
author = "orangc"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a52b5d49e1b4212d4a27beed1704b7ca9147f5759c712f0bdfddeae46cd57e3b"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"

[options]
acceptable-game-versions = ["1.21.6"]
