name = "Juniper"
author = "orangc"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e01a2ccd0988e049e278820b3fe7948c210ce5b8cf41e5d60d8adeee3d285c01"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"

[options]
acceptable-game-versions = ["1.21.6"]
datapack-folder = "datapacks"
