name = "Juniper"
author = "orangc"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67f09d3c988b22941069bd0bf2de6629ac8bfd9e8d282bd8cba8a6ddf252e323"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"

[options]
acceptable-game-versions = ["1.21.6"]
datapack-folder = "datapacks"
