name = "Juniper"
author = "orangc"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd1d57e63ac0111e20c1e9e12571a1a79668f56721ab1dd8a00bf7dc4d332144"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"

[options]
acceptable-game-versions = ["1.21.7"]
datapack-folder = "datapacks"
