name = "Juniper"
author = "orangc"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df56594ffbfd1d5c816820f091f21d0c0387a7108e1b438a1c102bf174f1dc5b"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"

[options]
acceptable-game-versions = ["1.21.7"]
datapack-folder = "datapacks"
