name = "Juniper"
author = "orangc"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1d711bd83ba73c32352bd7e94bd71f7a33a7fd537f3eda11918a22d76a3bb04"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"

[options]
acceptable-game-versions = ["1.21.6"]
datapack-folder = "datapacks"
